/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmusic;

import java.awt.Image;
import java.awt.List;
import java.io.File;
import java.nio.file.Paths;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author ZARD
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    AudioPlayer audioPlayer;
    String currentDirectory = "";
    JFileChooser chooser;
    Thread T_MAIN;
    List files;
    int cur_index = 0;
     private Preferences prefs;
    public MainFrame() {
        initComponents();
        audioPlayer = new AudioPlayer();
        files = new List();
         prefs = Preferences.userRoot().node(this.getClass().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        btnChoose = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbIamge = new javax.swing.JLabel();
        lbNameSong = new javax.swing.JLabel();
        lbArtist = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        slTIme = new javax.swing.JSlider();
        lbTime = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 27, 27));
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        titleBar.setBackground(new java.awt.Color(27, 27, 27));
        titleBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_16px_2.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_menu_16px.png"))); // NOI18N
        btnChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChooseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
            .addComponent(btnChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(27, 27, 27));

        lbIamge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIamge.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbNameSong.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbNameSong.setForeground(new java.awt.Color(215, 213, 214));
        lbNameSong.setText("Song Name");

        lbArtist.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbArtist.setForeground(new java.awt.Color(111, 167, 13));
        lbArtist.setText("By");

        btnPlay.setBackground(new java.awt.Color(27, 27, 27));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play_32px.png"))); // NOI18N
        btnPlay.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPlay.setBorderPainted(false);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        slTIme.setValue(0);

        lbTime.setForeground(new java.awt.Color(215, 213, 214));
        lbTime.setText("00:00/00:00");

        btnBack.setBackground(new java.awt.Color(27, 27, 27));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rewind_32px.png"))); // NOI18N
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(27, 27, 27));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fast_forward_32px.png"))); // NOI18N
        btnNext.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNext.setBorderPainted(false);
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(slTIme, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbIamge, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNameSong)
                                    .addComponent(lbArtist)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTime)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbNameSong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbArtist)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(slTIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTime))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbIamge, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
        currentDirectory = prefs.get("dir", currentDirectory);
        extract(currentDirectory);
        cur_index = 0;
        audioPlayer.setPlaySong(files.getItem(cur_index));
        lbNameSong.setText(audioPlayer.getSongName());
        lbArtist.setText("By "+audioPlayer.getArtist());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(audioPlayer.getImage()).getImage().getScaledInstance(lbIamge.getWidth(), lbIamge.getHeight(), Image.SCALE_DEFAULT));
        lbIamge.setIcon(imageIcon);
        cur_index++;
        if(cur_index >= files.getItemCount())
            cur_index = 0;
    }//GEN-LAST:event_formWindowOpened

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        
        if(T_MAIN != null && T_MAIN.isAlive()){
            audioPlayer.stop();
            T_MAIN.interrupt();
            while (true) {
               if(!T_MAIN.isAlive())
                   break;
                try {
                    Thread.sleep(50);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            ImageIcon image = new ImageIcon(Paths.get(".").toAbsolutePath().normalize().toString()+"\\src\\img\\play_32px.png");
            btnPlay.setIcon(image );
        }else{
            ImageIcon image = new ImageIcon(Paths.get(".").toAbsolutePath().normalize().toString()+"\\src\\img\\pause.png");
            btnPlay.setIcon(image );
            T_MAIN = new Thread(){
                @Override
                public void run(){
                    audioPlayer.play();
                        
                }
            };
            T_MAIN.start();
        }
       
        
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChooseMouseClicked
        // TODO add your handling code here:
        chooser = new JFileChooser(); 
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Choose");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
         chooser.setAcceptAllFileFilterUsed(false);
    //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            currentDirectory = chooser.getSelectedFile().toString();
            prefs.put("dir", currentDirectory);
            extract(currentDirectory);
        }else {
        }
    }//GEN-LAST:event_btnChooseMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        audioPlayer.setPlaySong(files.getItem(cur_index));
        lbNameSong.setText(audioPlayer.getSongName());
        lbArtist.setText("By "+audioPlayer.getArtist());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(audioPlayer.getImage()).getImage().getScaledInstance(lbIamge.getWidth(), lbIamge.getHeight(), Image.SCALE_DEFAULT));
        lbIamge.setIcon(imageIcon);
         cur_index++;
        if(cur_index >= files.getItemCount())
            cur_index = 0;
        audioPlayer.stop();
        if(T_MAIN != null &&T_MAIN.isAlive()){
            T_MAIN.interrupt();
            while (true) {
               if(!T_MAIN.isAlive())
                   break;
                try {
                    Thread.sleep(50);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            ImageIcon image = new ImageIcon(Paths.get(".").toAbsolutePath().normalize().toString()+"\\src\\img\\play_32px.png");
            btnPlay.setIcon(image );
        }
         T_MAIN = new Thread(){
                @Override
                public void run(){
                    ImageIcon image = new ImageIcon(Paths.get(".").toAbsolutePath().normalize().toString()+"\\src\\img\\pause.png");
                    btnPlay.setIcon(image );
                    audioPlayer.play();
                }
        };
        T_MAIN.start();
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
         audioPlayer.setPlaySong(files.getItem(cur_index));
        lbNameSong.setText(audioPlayer.getSongName());
        lbArtist.setText("By "+audioPlayer.getArtist());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(audioPlayer.getImage()).getImage().getScaledInstance(lbIamge.getWidth(), lbIamge.getHeight(), Image.SCALE_DEFAULT));
        lbIamge.setIcon(imageIcon);
         cur_index--;
        if(cur_index <= 0)
            cur_index = files.getItemCount()-1;
        audioPlayer.stop();
        if(T_MAIN != null &&T_MAIN.isAlive()){
            T_MAIN.interrupt();
            while (true) {
               if(!T_MAIN.isAlive())
                   break;
                try {
                    Thread.sleep(50);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            ImageIcon image = new ImageIcon(Paths.get(".").toAbsolutePath().normalize().toString()+"\\src\\img\\play_32px.png");
            btnPlay.setIcon(image );
        }
         T_MAIN = new Thread(){
                @Override
                public void run(){
                    ImageIcon image = new ImageIcon(Paths.get(".").toAbsolutePath().normalize().toString()+"\\src\\img\\pause.png");
                    btnPlay.setIcon(image );
                    audioPlayer.play();
                }
        };
        T_MAIN.start();
    }//GEN-LAST:event_btnBackMouseClicked
    private int tx, ty;
    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        // TODO add your handling code here:
        tx= evt.getX();
        ty=evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen() -tx, evt.getYOnScreen() -ty);
    }//GEN-LAST:event_titleBarMouseDragged

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public  void extract(String p){
        File f=new File(p);
        File l[]=f.listFiles();
        for(File x:l){
            if(x==null) return;
            if(x.isHidden()||!x.canRead()) continue;
            if(x.isDirectory()) extract(x.getPath());
            else if(x.getName().endsWith(".mp3")){
                System.out.println(x.getPath());
               files.add(x.getPath());
            }
              
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel btnChoose;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPlay;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbArtist;
    private javax.swing.JLabel lbIamge;
    private javax.swing.JLabel lbNameSong;
    public static javax.swing.JLabel lbTime;
    public static javax.swing.JSlider slTIme;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
